require: rubocop-rake

inherit_gem:
  gc_ruboconfig: rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
